config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  namespace :admin do
    get '/' => 'welcome#index'
    get 'dashboard' => 'welcome#dashboard', as: 'dashboard'
    get 'register' => 'welcome#register', as: 'register'
    post 'sign_in' => 'welcome#log_in', as: 'sign_in'
    post 'sign_up_' => 'welcome#sign_up_'
  end

  resources :beer_categories do
    resources :beers
  end

end

app/models/admin.rb
class Admin < User

end

app/models/beer.rb
class Beer < ActiveRecord::Base

  belongs_to :beer_category

  extend FriendlyId
  friendly_id :name

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :pair_with, presence: true
  validates :beer_category_id, presence: true

end

app/models/beer_category.rb
class BeerCategory < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name

  has_many :beers

  validates :name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.type == 'Admin'
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  layout 'admin'

  def authenticate_admin
    if current_user and current_user.admin?
      #proceed
    else
      redirect_to admin_path
    end
  end

  def authenticate_no_admin
    if current_user and current_user.admin?
      redirect_to admin_dashboard_path
    end
  end

end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < Admin::BaseController

  before_filter :authenticate_admin, only: [:dashboard]

  def index

  end

  def dashboard

  end

  def register

  end

  def log_in
    if sign_in_admin
      render status: :ok
    else
      render status: :unprocessable_entity, json: { errors: 'Email/Password combination wrong' }
    end
  end

  def sign_up_
    @user = Admin.new(user_params)
    if @user.save
      sign_in(@user)
      render status: :ok, json: { success: 'Successfully registred' }
    else
      render status: :unprocessable_entity, json: { errors: @user.errors.full_messages.first }
    end
  end

  private

  def sign_in_admin
    email = params[:email]
    password = params[:password]
    return false unless email.present? or password.present?
    admin = Admin.where(email: email).first
    return false unless admin.present?
    if admin.valid_password?(password)
      flash[:success] = "Signed in as #{admin.name}"
      sign_in(admin)
    end
  end

  def user_params
    params.require(:admin).permit(
        :name,
        :email,
        :password,
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  skip_before_filter :verify_authenticity_token

  layout 'admin'
end

app/controllers/beer_categories_controller.rb
class BeerCategoriesController < ApplicationController

  before_action :set_beer_category, only: [:edit, :update, :destroy]

  def index
    @beer_categories = BeerCategory.all
  end

  def new
    @beer_category = BeerCategory.friendly.new
  end

  def create
    @beer_category = BeerCategory.friendly.new(beer_category_params)
    if @beer_category.save
      render status: :ok, json: { success: 'Succssfully Created' }
    else
      render status: :unprocessable_entity, json: { errors: @beer_category.errors.full_messages.first }
    end

  end

  def edit

  end

  def update
    if @beer_category.update_attributes(beer_category_params)
      render status: :ok, json: { success: 'Succssfully updated' }
    else
      render status: :unprocessable_entity, json: { errors: @beer_category.errors.full_messages.first }
    end
  end

  def destroy
    @beer_category.destroy!
    redirect_to beers_path
  end

  private

  def set_beer_category
    @beer_category = BeerCategory.friendly.find params[:id]
  end

  def beer_category_params
    params.require(:beer_category).permit(:name)
  end

  def render_404
    render :template => 'error_pages/404', layout: 'admin', status: :not_found
  end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_action :set_beer, only: [:edit, :update, :destroy]
  before_action :set_beer_category

  def index
    @beers = @beer_category.beers
  end

  def new
    @beer = Beer.friendly.new
  end

  def create
    @beer = Beer.friendly.new(beer_params)
    if BeerCategory.all.map(&:name).include?(params[:beer_category_id])
      if @beer.save
        render status: :ok, json: { success: 'Succssfully Created' }
      else
        render status: :unprocessable_entity, json: { errors: @beer.errors.full_messages.first }
      end
    else
      render status: :not_found, json: { errors: 'Result not found' }
    end
  end

  def edit

  end

  def update
    if @beer.update_attributes(beer_params)
      render status: :ok, json: { success: 'Succssfully updated' }
    else
      render status: :unprocessable_entity, json: { errors: @beer.errors.full_messages.first }
    end
  end

  def destroy
    @beer.destroy!
    redirect_to beers_path
  end

  private

  def set_beer
    beer = Beer.friendly.where(name: params[:id]).first
    if beer.present?
      @beer = beer
    else
      render status: :not_found, json: { errors: 'Result not found' }
    end
  end

  def set_beer_category
    beer_category = BeerCategory.friendly.where(name: params[:beer_category_id]).first
    if beer_category.present?
      @beer_category = beer_category
    else
      render status: :not_found, json: { errors: 'Result not found' }
    end

  end

  def beer_params
    params.require(:beer).permit(:name,
                                 :price,
                                 :description,
                                 :pair_with).merge(beer_category_id: @beer_category.id)
  end

  # def render_404
  #   render :template => 'error_pages/404', layout: 'admin', status: :not_found
  # end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_alerts.html.erb
<% if flash[:success].present? %>
    <div class="alert alert-success" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:success] %>
    </div>
<%- end %>

<% if flash[:info].present? %>
    <div class="alert alert-info" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:info] %>
    </div>
<%- end %>

<% if flash[:warning].present? %>
    <div class="alert alert-warning" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:warning] %>
    </div>
<%- end %>

<% if flash[:error].present? %>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:error] %>
    </div>
<%- end %>

app/views/admin/shared/_header.html.erb
<nav class="navbar navbar-default top-navbar admin_header">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<span class="sidebar_nav_click">-->
        <!--<i class="fa fa-bars" aria-hidden="true"></i>-->
      <!--</span>-->
      <a class="navbar-brand" href="<%= admin_path %>">Admin</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><a href="Javascript:void(0)"><%= current_user.email %></a></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <%- end %>
      </ul>
    </div>
  </div>
</nav>

<script type="text/javascript" charset="utf-8">
//    $('.sidebar_nav_click').click(function(){
//        $('.toggle_class').toggle();
//        $('.right_content_con').toggleClass('col-sm-10 col-xs-9').toggleClass('col-sm-12 col-xs-12');
//    });
</script>

app/views/admin/welcome/dashboard.html.erb
<div class="admin-main-con">
  <div class='col-xs-12'>
    <h2>Your Dashboard</h2>
  </div>
  <div class="clearfix"></div>
</div>

app/views/admin/welcome/index.html.erb
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <fieldset>
      <legend>Admin Sign In</legend>
      <%= form_tag admin_sign_in_path do %>
          <div class="form-group">
            <%= label_tag :email %>
            <%= email_field_tag :email, params[:email], class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= label_tag :password %>
            <%= password_field_tag :password, '',class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= submit_tag 'Sign In', class: 'btn btn-success' %>
            <%= link_to 'Sign up', admin_register_path, class: 'btn btn-success' %>
          </div>
      <%- end %>
    </fieldset>
  </div>
  <div class="col-sm-4"></div>
</div>





<span class="abc">Click</span>

<script type="text/javascript" charset="utf-8">
//    $(".abc").click(function(){
//
//        var email = 'mayur.singh@jetsetgo.in'
//        var password = 'jetsetgo123'
//
//        $.post('admin/sign_in', {email: email, password: password})
//                .done(function(msg){
//                    alert(msg);
//                })
//                .fail(function(xhr, status, error) {
//                    // error handling
//                    $(".otp-error").removeClass('hidden')
//
//                });
//    });


$(".abc").click(function(){

    var email = 'mayur.singh2@jetsetgo.in'
    var password = 'jetsetgo123'
    var name = 'Mayur'

    $.post('admin/sign_up_', {admin: {name: '', email: email, password: password}})
            .done(function(msg){
                alert(msg);
            })
            .fail(function(xhr, status, error) {
                // error handling
                $(".otp-error").removeClass('hidden')

            });
});
</script>

app/views/admin/welcome/register.html.erb
<div class="row">
  <div class="col-sm-4">

  </div>
  <div class="col-sm-4">
    <div class="mfp-dialog clearfix" id="nav-login-dialog">
      <h3 class="widget-title">Register</h3>
      <p>Welcome, Register to get Enter</p>
      <hr />
      <%= simple_form_for :admin, :url => admin_sign_up__path do |f| %>
          <div class="form-group">
            <%= f.input :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.input :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.input :password, class: 'form-control' %>
          </div>
          <%= submit_tag 'Submit', class: 'btn btn-primary' %>
          <%= link_to 'Already registred', admin_path, class: 'btn btn-primary' %>
      <%- end %>
    </div>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/beer_categories/_form.html.erb
<%= simple_form_for [@beer_category] do |f| %>
    <%#= f.input :beer %>
    <%= f.input :name %>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/beer_categories/edit.html.erb
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <div class="text-center"><h2>Edit Beer Category</h2></div>
    <%= render partial: 'form' %>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/beer_categories/index.html.erb
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-8">
    <div class="text-center"><h2>Beer Category List</h2></div>
    <ul class="list-inline">
      <li>
        <%= link_to 'Add Beer Category', new_beer_category_path, class: 'btn btn-primary' %>
      </li>

    </ul>
  </div>
  <div class="col-xs-2"></div>
</div>

<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-8">
    <table class="table table-striped">
      <tr class="info">
        <th>Id</th>
        <th>Beer</th>
        <th>Action</th>
      </tr>
      <tr>
        <% @beer_categories.each do |beer_category| %>
          <tr>
            <td><%= beer_category.id %></td>
            <td><%= beer_category.name %></td>
            <td>
              <%= link_to edit_beer_category_path(beer_category) do %>
                  <i class="fa fa-edit"></i>
              <% end %>

              <%= link_to 'check', beer_category_beers_path(beer_category) %>

              <%#= link_to beer_beer_category_path(beer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' do %>
                  <!--<i class="fa fa-trash"></i>-->
              <%# end %>

            </td>
          </tr>
      <% end %>
      </tr>
    </table>
  </div>
  <div class="col-xs-2"></div>
</div>

app/views/beer_categories/new.html.erb
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <div class="text-center">
      <h2>New Beer Category</h2>
    </div>
    <%= render partial: 'form' %>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/beers/_form.html.erb
<%= simple_form_for [@beer_category, @beer] do |f| %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :pair_with %>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/beers/edit.html.erb
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <div class="text-center"><h2>Edit Beer</h2></div>
    <%= render partial: 'form' %>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/beers/index.html.erb
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-8">
    <div class="text-center"><h2>Beer List</h2></div>
    <ul class="list-inline">
      <li>
        <%= link_to 'Add Beer', new_beer_category_beer_path, class: 'btn btn-primary' %>
      </li>

    </ul>
  </div>
  <div class="col-xs-2"></div>
</div>

<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-8">
    <table class="table table-striped">
      <tr class="info">
        <!--<th>Id</th>-->
        <th>Beer</th>
        <th>Price</th>
        <th>Description</th>
        <th>Pair with</th>
        <th>Action</th>
      </tr>
      <tr>
        <% @beers.each do |beer| %>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.price %></td>
            <td><%= beer.description %></td>
            <td><%= beer.pair_with %></td>
            <td>
              <%= link_to edit_beer_category_beer_path(@beer_category, beer) do %>
                  <i class="fa fa-edit"></i>
              <% end %>
              <%#= link_to beer_category_beer_path(beer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' do %>
                  <!--<i class="fa fa-trash"></i>-->
              <%# end %>
              <%#= link_to 'Beer Categories', beer_beer_categories_path(beer) %>
              <%#= link_to 'Toggle', admin_airport_path(airport), method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
      <% end %>
      </tr>
    </table>
  </div>
  <div class="col-xs-2"></div>
</div>

app/views/beers/new.html.erb
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <div class="text-center">
      <h2>New Beer</h2>
    </div>
    <%= render partial: 'form' %>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/error_pages/404.html.erb
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <h2>This is ERROR Page for status 404</h2>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dummy | Admin</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render partial: 'admin/shared/header' %>
<div class="container-fluid">
  <% if user_signed_in? and current_user.admin? %>
      <div class="row">
        <div class="col-sm-2 col-xs-3 toggle_class no-padding" style="display: none">
          <%#= render partial: 'admin/shared/sidebar' %>
        </div>
        <div class="col-sm-12 col-xs-12 right_content_con no-padding">
          <%= render partial: 'admin/shared/alerts' %>
          <%= yield %>
        </div>
      </div>
  <%- else %>
      <%= render partial: 'admin/shared/alerts' %>
      <%= yield %>
  <%- end %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dummy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <h2>Welcome</h2>
    <% if user_signed_in? and current_user.admin? %>
        <%= link_to 'Dashboard', admin_dashboard_path, class: 'btn btn-primary' %>
    <% else %>
        <%= link_to 'login', admin_path, class: 'btn btn-primary' %>
    <% end %>
    <%= link_to 'Beer Categories', beer_categories_path, class: 'btn btn-primary' %>
    <%#= link_to 'Beers', beers_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-sm-4"></div>
</div>